        DB(ahosts)
        DB(ahostsv4)
        DB(ahostsv6)
        DB(hosts)
        DB(networks)
        DB(password)
        DB(protocols)
        DB(ethers)
        DB(group)
        DB(services)
        DB(shadow)
#if HAVE_ALIASES
        DB(aliases)
#endif
#if HAVE_GSHADOW
        DB(gshadow)
#endif
        DB(initgroups)
#if HAVE_NETGROUP
        DB(netgroup)
#endif
#if HAVE_RPC
        DB(rpc)
#endif
